# encoding: utf-8
# module renderdoc
# from c:\WorkSpace\Tools\rdcTest\lib\windows\renderdoc.pyd
# by generator 1.147
# no doc

# imports
import enum as __enum

from typing import List, Tuple, Callable, Any


class MessageCategory(__enum.IntEnum):
    """
    The type of issue that a debug message is about.
    
    .. data:: Application_Defined
    
      This message was generated by the application.
    
    .. data:: Miscellaneous
    
      This message doesn't fall into any other pre-defined category.
    
    .. data:: Initialization
    
      This message is about initialisation or creation of objects.
    
    .. data:: Cleanup
    
      This message is about cleanup, destruction or shutdown of objects.
    
    .. data:: Compilation
    
      This message is about compilation of shaders.
    
    .. data:: State_Creation
    
      This message is about creating unified state objects.
    
    .. data:: State_Setting
    
      This message is about changing current pipeline state.
    
    .. data:: State_Getting
    
      This message is about fetching or retrieving current pipeline state.
    
    .. data:: Resource_Manipulation
    
      This message is about updating or changing a resource's properties or contents.
    
    .. data:: Execution
    
      This message is about performing work.
    
    .. data:: Shaders
    
      This message is about the use, syntax, binding or linkage of shaders.
    
    .. data:: Deprecated
    
      This message is about the use of deprecated functionality.
    
    .. data:: Undefined
    
      This message is about the use of undefined behaviour.
    
    .. data:: Portability
    
      This message is about behaviour that could be or is not portable between different environments.
    
    .. data:: Performance
    
      This message is about performance problems or pitfalls.
    """
    def __init__(self, *args, **kwargs): # real signature unknown
        pass

    Application_Defined = 0
    """ This message was generated by the application. """

    Cleanup = 3
    """ This message is about cleanup, destruction or shutdown of objects. """

    Compilation = 4
    """ This message is about compilation of shaders. """

    Deprecated = 11
    """ This message is about the use of deprecated functionality. """

    Execution = 9
    """ This message is about performing work. """

    Initialization = 2
    """ This message is about initialisation or creation of objects. """

    Miscellaneous = 1
    """ This message doesn't fall into any other pre-defined category. """

    Performance = 14
    """ This message is about performance problems or pitfalls. """

    Portability = 13
    """ This message is about behaviour that could be or is not portable between different environments. """

    Resource_Manipulation = 8
    """ This message is about updating or changing a resource's properties or contents. """

    Shaders = 10
    """ This message is about the use, syntax, binding or linkage of shaders. """

    State_Creation = 5
    """ This message is about creating unified state objects. """

    State_Getting = 7
    """ This message is about fetching or retrieving current pipeline state. """

    State_Setting = 6
    """ This message is about changing current pipeline state. """

    Undefined = 12
    """ This message is about the use of undefined behaviour. """



